# Generated by Django 4.1.1 on 2022-09-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=20)),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('dead', models.BooleanField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=20)),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('dead', models.BooleanField(blank=True, max_length=100, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=20)),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('dead', models.BooleanField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
