# Generated by Django 4.1.1 on 2022-09-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='order_id',
        ),
        migrations.AddField(
            model_name='polloption',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
