# Generated by Django 4.1.1 on 2022-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
