# Generated by Django 4.1.1 on 2022-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AddField(
            model_name='polloption',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
