# Generated by Django 4.1.1 on 2022-09-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_polloption_order_id_polloption_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='polloption',
            old_name='parent',
            new_name='post',
        ),
    ]
