# Generated by Django 4.0.4 on 2022-09-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment_by_hackernews_polloption_by_hackernews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='by_hackernews',
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='by_hackernews',
        ),
        migrations.RemoveField(
            model_name='post',
            name='by_hackernews',
        ),
    ]
